import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MobileLayout from "@/components/MobileLayout";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning: ColorZilla 등 브라우저 확장이 추가하는 속성으로 인한 hydration 경고 방지 */}
      <body className={`${pretendard.variable} antialiased`} suppressHydrationWarning>
        <MobileLayout>{children}</MobileLayout>
      </body>
    </html>
  );
}
